# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CrowdAI
tagline:          ''
description:      'Knowledge Base'
url:              http://hyde.getpoole.com
baseurl:          /Knowledge-Base

author:
  name:           'S.P. Mohanty'
  url:            https://twitter.com/MeMohanty


# Custom vars
