# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CrowdAI
tagline:          ''
description:      'A tutorial on how to get started with the PlantVillage Classification Challenge on CrowdAI'
url:              http://hyde.getpoole.com
baseurl:          /PlantVillage-Classification

author:
  name:           'S.P. Mohanty'
  url:            https://twitter.com/MeMohanty


# Custom vars
highlighter: pygments
